# --------------
# -- Settings --
# --------------

# Ignore this. This is only if you're hosting this in a sub-folder.
# If you're using GitHub pages, they automatically override this with the right value.
baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "http://hackbordeaux.com"
#url: "http://localhost:4000"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-43729070-14"

# Let people connect & engage with you through social media.
social:
  twitter_handle: "MLHacks"
  mail: "sponsor@hackbordeaux.com"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "HackBordeaux | 6th-7th May 2017"
  description: "Student-run hackathon at ENSEIRB-MATMECA, Bordeaux, France"
  image:       "https://www.bordeaux-inp.fr/system/files/enseirb-matmeca_0.jpg"

# Event information.
event:
  name:        "HackBordeaux"
  description: "Student-run hackathon"
  date:        "6th-7th May 2017"
  location:    "ENSEIRB-MATMECA, Bordeaux, France"
  image:       "/images/banner.png"

  trust_badge:
    year:   "2017"  # season year
    region: "eu"    # "na" or "eu"
    color:  "white" # "white", "black", "gray", "red", "blue" or "yellow"

  hero:
    image: "/images/logo.png"
    links:
      #- text: "Apply"
        #my_mlh:
          #client_id:    "0e2f9fc2921d3ad3e12ae900af630d09382e1b3dc1b5b50de2b01b70ad64dbee"
          #redirect_uri: "https://mlh.github.io/mlh-hackathon-boilerplate/success.html"
      #- text: "Sponsor"
        #href: "mailto:sponsor@hackbordeaux.com"

  about:
    description: >
      HackBordeaux is a student run hackathon in collaboration with <a href="#sponsors">sponsoring companies & startups</a>, held at Bordeaux-INP in Bordeaux, France on the 6th-7th May, 2017


      So come join up to 200 passionate like-minded people on this adventure!
      Let's build amazing things, learn even more and share awesome experiences from around Europe!

  #planning data
  planning:
    saturday:
    - time: "09:00 AM"
      content: "Registering, welcoming area"
    - time: "09:30 AM"
      content: "Chilling, breakfast, getting to know everyone"
    - time: "10:30 AM"
      content: "Opening ceremony"
    - time: "12:00 PM"
      content: "Pairing up session"
    - time: "12:30 PM"
      content: "Hacking starts !"
    - time: "01:00 PM"
      content: "Lunch"
    - time: "02:00 PM"
      content: "Parallel workshops | activities | mini-events"
    - time: "07:00 PM"
      content: "Dinner"
    - time: "07:30 PM"
      content: "Parallel activities | mini-events"
    - time: "10:00 PM"
      content: "Resting areas open"
    - time: "12:00 AM"
      content: "Midnight pizza !"
    sunday:
    - time: "08:30 AM"
      content: "Breakfast"
    - time: "12:30 PM"
      content: "Hacking ends !"
    - time: "01:00 PM"
      content: "Lunch"
    - time: "02:00 PM"
      content: "Hacking Expo"
    - time: "03:45 PM"
      content: "Challenges winners announced"
    - time: "04:00 PM"
      content: "Challenges winners presentations"
    - time: "05:00 PM"
      content: "1st | 2nd | 3rd places winners announced"
    - time: "05:00 PM"
      content: "Ending ceremony"

      # Info Sections
  info:
    image: "images/INP_building.jpg"
    sections:
      - image: "images/present/1.jpg"
      - image: "images/present/9.jpg"
      - image: "images/present/6.jpg"

    help: "Any questions related to the event? Send an email to info@hackbordeaux.com"

  # Abroad"
  abroad:
    description: "Are you coming from another country or city? Awesome! Join us for a tour of Bordeaux on Friday and get to meet everyone. We will take care of you  and settle everything so you can be ready for HackBordeaux the next day!"
    sections:
    help: >
      Any questions or do want to get to know us? Send an email to [info@hackbordeaux.com](mailto:info@hackbordeaux.com) or simply contact us on <a href="#about">social networks</a>
    video : "https://www.youtube.com/embed/VaZA-qD22X0"
  # Frequently asked questions.
  faq:
    - question: "What is a hackathon?"
      answer: >
        A [MLH](https://mlh.io) hackathon is a creative and social event where students come together, share ideas and build cool software & hardware hacks during 24 hours.


        You learn immensely, interact with startups & companies and get to meet like-minded people from around the world. Don't worry it's [very beginner friendly](https://medium.com/@tfogo/hackathons-are-for-beginners-77a9c9c0e000#.cj21niskl)!
    - question: "How much does it cost?"
      answer: >
        Nothing. Attending a MLH hackathon is free, and we'd like to thank our awesome <a href="#sponsors">sponsors</a> who made it possible!
    - question: "Do I need to be a student to attend?"
      answer: >
        Yes. Only students who are currently enrolled at a college/university or
        have graduated within the past 12 months are eligible to attend.


        However, are you interested in this event or totally excited about it?
        You can also be a [mentor](https://mlh.io/mentors) helping students during their hacks! [Contact us](mailto:info@hackbordeaux.com)!
    - question: "Where is the event?"
      answer: >
        The event is being hosted at <a href="#location">Bordeaux-INP, ENSEIRB-MATMECA</a>.
    - question: "Do you provide travel reimbursement?"
      answer: >
        Yes, thanks to our sponsors we are able to provide up to 20euros ! More info soon.
    - question: "What is the maximum size of a team ?"
      answer: >
        You can be 4 hackers in each team!
    - question: "What is Major League Hacking?"
      answer: >
        Major League Hacking is [the official student hackathon league](https://mlh.io) in North America & Europe.
        We work with over 200 Member Events and empower over 70,000 students every year.
    - question: "Is there a code of conduct?"
      answer: >
        Yes there is. We enforce it very strongly. You can [find it here](https://static.mlh.io/docs/mlh-code-of-conduct.pdf).

  # Sponsors, TODO populate and yml structure for gold, silver, bronze, general partners loop
  sponsors:
    invite: "Interested in sponsoring HackBordeaux?"
    gold:
    - image : "images/sponsors/newmips.png"
      link: "https://www.newmips.com"
    silver:
    - image : "images/sponsors/algolia.png"
      link: "https://www.algolia.com"
    - image : "images/sponsors/soprasteria.png"
      link: "https://www.soprasteria.com/en"
    - image : "images/sponsors/lectra-rouge-gris.png"
      link: "https://www.lectra.com/en"
    partners:
    - image : "images/sponsors/partners/mlh.png"
      link: "https://mlh.io"
    - image : "images/sponsors/partners/bordeaux-inp.png"
      link: "https://enseirb-matmeca.bordeaux-inp.fr"
    - image : "images/sponsors/partners/github.svg"
      link: "https://github.com"
    - image : "images/sponsors/partners/bloomberg.svg"
      link: "https://bloomberg.com"
    - image : "images/sponsors/partners/amazon-web-services.svg"
      link: "https://aws.amazon.com"
    - image :"images/sponsors/clay.png"
      link :"http://www.claymusic.fr/"
    food:
    - image: "images/sponsors/partners/food/asobo.png"
      link: http://www.asobostudio.com/
    - image: "images/sponsors/partners/food/herbalife-nutrition.png"
      link: http://www.herbalife.com/
    - image: "images/sponsors/partners/food/boitepizza.png"
      link: https://www.laboiteapizza.com/
    - image: "images/sponsors/partners/food/nuit-blanche.jpg"
      link: https://www.facebook.com/nuit.blanche.92/
    domains:
    - image: "images/sponsors/partners/domains/tech.png"
      link: http://get.tech/
    hardware:
    - image: "images/sponsors/partners/hardware/sigfox.png"
      link: https://www.sigfox.com/en

  # This is the message you'll receive once you've registered.
  register:
    message: >
      You'll receive more information closer to the hackathon.

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
